scripts/daily_plot.py
The addition of handling date cutover for updating charts introduced a bug on systems whose timezones are behind UTC. Specifically, the 'localtime' modifier to DATE() attempts to interpret the date to the left as UTC, and convert to localtime. The result is that in timezones behind UTC, the date selected is always 1 earlier than intended.
No timezone conversion is needed. We need a date for today, or 24h ago, to match for the where clause in the query. Since the data in the DB is in localtime, and the output of python datetime is also in localtime, it's good enough to just turn it into a YYYY-MM-DD without any timezone conversion at all.
Here's a demonstration of calling DATE() in various ways in North America EST:
sqlite> select DATE('now');
2024-02-26
sqlite> select DATETIME('now'); …
=> Remove utc to localtime conversion from daily_plot.py

scripts/system_controls.php
Pointer is to the original repo when checking for latest commits to display hash. Change to Nachtzuster repo to reflect proper hash.
=> Change repo in System Controls

scripts/plotly_streamlit.py
This bug has affected me for a while! I finally got to fixing it now that there's an active fork to benefit from the fix. :)
Sunrise/sunset scatter plots are misplaced for
* Date ranges that are a subset of the entire DB date range
* Species whose first/last detections are inside the bounds of the current date range.
This fixes those problems by using the same date range as the heatmap data. Before, it was making a simple date count from "now" without paying attention to the date bounds of the heatmap data.
To see these heatmaps and reproduce the problem: 
* launch "Species Stats"
* On the left, select "DAILY"
* (a) use the date range sliders to narrow the date range and pick a species on the right, or
* (b) leave the date range as is, and pick a species on the right that you have sparse …
=> Fix sunrise/sunset scatter plots

scripts/plotly_streamlit.py
Introduces usage of get_settings for determining latitude and longitude for sunrise and sunset scatter plots, as suggested in #16 .
With changes implemented, I deliberately broke my lat/lon config. Sunrise/sunset times change (e.g. are broken too) :
Fixing lat/lon again, the sunrise/sunset times are displayed as expected:
=> Read lat/lon from config

scripts/daily_plot.py
When the `chart_viewer.service` starts, there is a warning : `UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator."`
This should fix it, at least tested on my system (rpi4 aarch64) but should be transversal to all systems
=> Fix : set_ticklabels warning

scripts/exclude_list.php, scripts/include_list.php
Issue : on mobile, the user input box to make easier to go to a specie doesn't work as there is no "enter touch". This means that people have to manually find the specie to include or exclude, which is cumbersome as it starts with the scientific name
Proposed solution : use the input box for filtering of the list instead. It works on both browser (tested on windows with edge) and mobile (tested on ios with safari and edge)
I've used the same logic of filtering for my other PR which proposes to convert an identified specie to another (and correct database + files storage location)
Of course, it's as you want, perhaps it is a bit specific based on my own usage of the app :-)
=> Feat : use text input for filtering of exclude_list & include_list

scripts/config.php, scripts/utils/notifications.py
Added $maskedlistenurl as an option for apprise notifications.
Tries to close #80
=> Add additional apprise notification option

scripts/common.php, scripts/play.php
Currently, the play.php page accessed through Recordings or Today species only shows as a text the common name of the specie
This PR takes advantage of the new site_info function to add a ebird/allaboutbirds link to the title, allowing a faster access and a bit more harmonized management with other pages
=> Feat : Add site_info to the title of the species accessed through Recordings or Unique species

scripts/play.php
When we corrected the darkmode script we missed the absence of css style in the dropdown from the modal box used to change a detected species.
It will now use the "testbtn" style as for all dropdowns
=> Fix : set testbtn as css style for species change dropdown (align with all dropdown)

scripts/advanced.php
When looking at the Audio Settings in the advanced section the spacing between the setting and description bugged me. This is a small change to move the description to under the actual setting.
Current:
Updated:
=> Cleanup the Audio Settings section a little

scripts/utils/helpers.py
I run a few Docker containers on the same system that runs BirdNET-Pi and I've noticed this can cause issues with the `lsof` command that looks for `.wav` files to process. Here is what I would see when Docker is running:
```
12:12:59--- lsof: WARNING: can't stat() overlay file system /var/lib/docker/overlay2/7ee00bfe5a0d2d841a053baaf7fb23b47f09c056c2806568ec9e53762bf4cdea/merged
12:12:59---      Output information may be incomplete.
12:12:59---lsof: WARNING: can't stat() overlay file system /var/lib/docker/overlay2/739026a51809ca99ba0244fd1999abb2fe074659d984b4ec6b4dfaf560dc8c23/merged
12:12:59---      Output information may be incomplete.
12:12:59---lsof: WARNING: can't stat() nsfs file system /run/docker/netns/8a59faa891ac
12:12:59---      Output information may be incomplete. …
```
=> Fix: Ignore warnings from `lsof` output

scripts/server.py
https://github.com/Nachtzuster/BirdNET-Pi/issues/138
Error messages to explain why detections would not be kept
=> Feat : error messages for detections rejections #138

.gitignore
All local databases should be ignored by git. They are specific to each installation and do not belong in the repository.
=> Ignore all local databases

scripts/play.php
Not very useful but prettier :-)
Tested on windows and ios
Before : 
After :
=> UI : Convert checkbox to toggleswitch

scripts/server.py, scripts/utils/helpers.py, scripts/utils/reporting.py
Fixes https://github.com/Nachtzuster/BirdNET-Pi/issues/227
**Problem**: Currently, the detection timestamp stored in the database corresponds to the start time of the original audio file. As a result, several detections generated from the same file all share the same timestamp, even though these detections actually occurred at different moments within that file.
**Proposed change**: Adjust the timestamp stored in the database to reflect the actual detection time, by adding the delay in seconds between the start of the audio file and the start of the detection.
* **Datetime-related attributes** are added to the `Detection` class in `helpers.py`:
* Attributes (types in parenthesis):
* `datetime (datetime.datetime)`: The actual detection start time, calculated as the audio file's start …
=> Adjust timestamps to reflect actual detection time instead of audio file start time

scripts/overview.php, scripts/todays_detections.php
Proposal to solved https://github.com/Nachtzuster/BirdNET-Pi/issues/233 : minigraphs are empty when searching a species with ' in it's common name as both " " and "'" are replaced with "_" to sanitize urls
=> Fix : correct minigraphs for names with apostrophs

scripts/utils/reporting.py
Add back an identifier of the RTSP stream an extracted file was derived from to the file name of an extracted birdsong.  The identifier thereby becomes included in the filename listed in birds.db, and hence is accessible for any post-processing utilities that may require the location of the microphone that picked up a particular birdsong.  Knowing the detection location of a birdsong has the potential to be very useful, for example for later examining camera footage to see if images of the identified bird are available.  
This PR augments the Nov 20 2024 commit 'Use detection time instead of origin audio file time in DB' by restoring the RTSP stream ID into the extracted birdsong file name.
=> Restore unique RTSP identifier to extracted file names

scripts/common.php
This PR aims to fix https://github.com/Nachtzuster/BirdNET-Pi/issues/243.
I previously never provided a password which worked OK,  but `isset($_SERVER['PHP_AUTH_PW'])` now returns `false`, which means `if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {` returns `false` and so returns an overall result of `false` (which fails auth).
The change below removes the `if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {` check entirely as it seems to work correctly without it.
I honestly don't know why this is now necessary as I can't see any recent code changes, perhaps a recent PHP upgrade caused this?
=> $_SERVER['PHP_AUTH_PW'] isn't always sent

scripts/advanced.php, scripts/disk_check.sh, scripts/install_config.sh, scripts/update_birdnet_snippets.sh
**Problem**
Currently, the threshold at which files are purged from disk is hard coded at 95%. Depending on users and systems this can be either too high or too low. Editing the threshold to adjust for user preferences would have to be done in the script where the disk cleanup is run. This is less than ideal because it puts this control out of scope for less technical users and would be wiped out or cause issues during updates.
**Proposed Change**
Add a purge threshold setting. This setting allows the user to control at what filled percentage the purge activities are run.
**Detailed Description of Changes**
1. Adds a configuration item to `advanced.php` to set the purge threshold. Also adds relevant description and warnings.
- The current setting allow a range of 20-99 percent. These felt …
=> Add Purge Threshold

scripts/play.php
Issue : currently when there is a high number of recordings (I have 3k recordings on my disk for my top bird), the browsers try to load all spectrograms leading to high memory usage and blocking playback until everything is buffered
Proposal : new toggle to limit by default to top 50 recordings - anyway who needs more than this.
Advantages : MUCH faster opening for the different species. The code is aligned with pre-existing code.
=> UI : recordings limit

homepage/static/custom-audio-player.js, homepage/views.php, scripts/overview.php, scripts/play.php, scripts/todays_detections.php
Hi, I've developed a redesigned audio player that will be added to the HA addon. It might interest you also.
Objective : 
- Fix mobile issues : spectrogram disappears once playback is started & no download button
- Embed gain control as default volume is often too low compared to other playbacks
- Consistency on player appearance (currently it was using the video controls which is system dependent)
Implementation : 
- Custom audio javascript which is self-contained
- Resource efficient : lazy loading (file ; audio nodes) and releasing to avoid using too much resources
- Code for frequency shift and auto-refresh adapted for the new controler
Features : 
- Clean modern UI
- Mouse & touch aware
- Allow to start from a specific point by clicking on the spectrogram
- Consistent accross devices …
=> New feat : Redesigned audio player

homepage/static/custom-audio-player.js
Currently the progress bar is visible while loading the image. This fixes this providing a cleaner look
=> Load progress bar after image on audio player

scripts/server.py
I have owls nearby that somehow have a very low Species Occurrence Frequency Threshold and get discarded. I don't want to lower the overall threshold where it will incorrectly start detecting rare birds. I'd like an exception for the owls I know that are nearby. The whitelist should be the system to do so, however, it was never implemented in `server.py`.
Similar to: https://github.com/Nachtzuster/BirdNET-Pi/discussions/265
=> Bugfix: whitelist_species_list.txt will now overrule the Species Occurrence Frequency Threshold
